config/routes.rb
Rails.application.routes.draw do
  resources :rating_restaurants

    root 'rating_restaurants#index'

end

app/models/rating_restaurant.rb
class RatingRestaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rating_restaurants_controller.rb
class RatingRestaurantsController < ApplicationController
  before_action :set_rating_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /rating_restaurants
  # GET /rating_restaurants.json
  def index
    @rating_restaurants = RatingRestaurant.all
  end

  # GET /rating_restaurants/1
  # GET /rating_restaurants/1.json
  def show
  end

  # GET /rating_restaurants/new
  def new
    @rating_restaurant = RatingRestaurant.new
  end

  # GET /rating_restaurants/1/edit
  def edit
  end

  # POST /rating_restaurants
  # POST /rating_restaurants.json
  def create
    @rating_restaurant = RatingRestaurant.new(rating_restaurant_params)

    respond_to do |format|
      if @rating_restaurant.save
        format.html { redirect_to @rating_restaurant, notice: 'Rating restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @rating_restaurant }
      else
        format.html { render :new }
        format.json { render json: @rating_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rating_restaurants/1
  # PATCH/PUT /rating_restaurants/1.json
  def update
    respond_to do |format|
      if @rating_restaurant.update(rating_restaurant_params)
        format.html { redirect_to @rating_restaurant, notice: 'Rating restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating_restaurant }
      else
        format.html { render :edit }
        format.json { render json: @rating_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rating_restaurants/1
  # DELETE /rating_restaurants/1.json
  def destroy
    @rating_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to rating_restaurants_url, notice: 'Rating restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating_restaurant
      @rating_restaurant = RatingRestaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_restaurant_params
      params.require(:rating_restaurant).permit(:comments, :star)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rating_restaurants_helper.rb
module RatingRestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- <!-- CSS file for Star Rating Pluggin -->
<link rel="stylesheet" type="text/css" href="jRating.jquery.css" media="screen" />
<!-- jQuery file for Star Rating Pluggin -->
<script type="text/javascript" src="jRating.jquery.js"></script> -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rating_restaurants/_form.html.erb
<%= form_for(@rating_restaurant) do |f| %>
  <% if @rating_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating_restaurant.errors.count, "error") %> prohibited this rating_restaurant from being saved:</h2>

      <ul>
      <% @rating_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :star %><br>
    <%= f.number_field :star %>

  </div>

<div class="basic" data-average="12" data-id="1"></div>

<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/rating_restaurants/edit.html.erb
<h1>Editing rating_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating_restaurant %> |
<%= link_to 'Back', rating_restaurants_path %>

app/views/rating_restaurants/index.html.erb
<h1>Listing rating_restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Comments</th>
      <th>Star</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rating_restaurants.each do |rating_restaurant| %>
      <tr>
        <td><%= rating_restaurant.comments %></td>
        <td><%= rating_restaurant.star %></td>
        <td><%= link_to 'Show', rating_restaurant %></td>
        <td><%= link_to 'Edit', edit_rating_restaurant_path(rating_restaurant) %></td>
        <td><%= link_to 'Destroy', rating_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating restaurant', new_rating_restaurant_path %>

app/views/rating_restaurants/new.html.erb
<h1>New rating_restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', rating_restaurants_path %>

app/views/rating_restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comments:</strong>
  <%= @rating_restaurant.comments %>
</p>

<p>
  <strong>Star:</strong>
  <%= @rating_restaurant.star %>
</p>

<%= link_to 'Edit', edit_rating_restaurant_path(@rating_restaurant) %> |
<%= link_to 'Back', rating_restaurants_path %>